on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  ci:
    name: continuous integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@4.1.0
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0
      - name: pnpm install and build
        run: |
          pnpm install -no-hoist
          pnpm -r run build
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          path: .
    
